language: java
jdk:
  - openjdk7

env:
  - BUILD=R
  - BUILD=java

before_install:
  - if [[ $BUILD == 'R' ]]; then sudo add-apt-repository ppa:marutter/rrutter -y; sudo apt-get update; sudo apt-get install r-base; curl https://raw.githubusercontent.com/dfci-cccb/raven/19765d22cd4cb2e473eed0e3838850efb948fe17/R/raven.R -o /tmp/raven.R; fi

install:
  - if [[ $BUILD == 'R' ]]; then echo "source ('/tmp/raven.R'); raven (inspect (), fetch (), import (environment (NULL)), install ())" | R --no-save; fi
  - if [[ $BUILD == 'java' ]]; then mvn install -DskipTests; fi

script:
  - if [[ $BUILD == 'R' ]]; then echo "source ('/tmp/raven.R'); raven ()" | R --no-save; fi
  - if [[ $BUILD == 'java' ]]; then mvn test; fi
