language: java
jdk:
  - openjdk7

env:
  - BUILD=R
  - BUILD=java
  - BUILD=web

before_install:
  - if [[ $BUILD == 'R' ]]; then sudo add-apt-repository ppa:marutter/rrutter -y && sudo apt-get update && sudo apt-get install r-base && sudo R -e "install.packages ('devtools', repos='http://cran.rstudio.com/'); devtools::install_github ('dfci-cccb/raven', ref = 'cdebc056f6c73bdf8d7b933a1c31cc7b169aa289')"; fi
  - if [[ $BUILD == 'web' ]]; then sudo apt-add-repository ppa:chris-lea/node.js -y && sudo apt-get update && sudo apt-get install nodejs && npm install -g bower gulp && npm install; fi

install:
  - if [[ $BUILD == 'R' ]]; then R -e "if (require ('raven')) raven (inspect (), fetch (), import (environment (NULL)), install ())"; fi
  - if [[ $BUILD == 'java' ]]; then mvn install -DskipTests; fi
  - if [[ $BUILD == 'web' ]]; then gulp build; fi

script:
  - if [[ $BUILD == 'R' ]]; then R -e "if (require ('raven')) raven ()"; fi
  - if [[ $BUILD == 'java' ]]; then mvn test; fi
  - if [[ $BUILD == 'web' ]]; then gulp test; fi
