language: java
jdk:
  - openjdk7

env:
  - BUILD=R
  - BUILD=java

before_install:
  - if [[ $BUILD == 'R' ]]; then sudo add-apt-repository ppa:marutter/rrutter -y && sudo apt-get update && sudo apt-get install r-base && R CMD INSTALL devtools && R -e "devtools::install_github ('dfci-cccb/raven', ref = '12342d03a31225ca3afb1fe6391dab072cb90170')"; fi

install:
  - if [[ $BUILD == 'R' ]]; then R -e "raven::raven (inspect (), fetch (), import (environment (NULL)), install ())"; fi
  - if [[ $BUILD == 'java' ]]; then mvn install -DskipTests; fi

script:
  - if [[ $BUILD == 'R' ]]; then R -e "raven::raven ()"; fi
  - if [[ $BUILD == 'java' ]]; then mvn test; fi
